/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-02-27 05:20:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>AceBank — Modern Banking</title>\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --bg:        #080c14;\n");
      out.write("            --bg2:       #0d1220;\n");
      out.write("            --bg3:       #111827;\n");
      out.write("            --surface:   rgba(255,255,255,0.04);\n");
      out.write("            --surface2:  rgba(255,255,255,0.07);\n");
      out.write("            --border:    rgba(255,255,255,0.08);\n");
      out.write("            --glow:      rgba(0,212,170,0.35);\n");
      out.write("            --cyan:      #00d4aa;\n");
      out.write("            --cyan-dim:  #00a882;\n");
      out.write("            --cyan-bg:   rgba(0,212,170,0.08);\n");
      out.write("            --cyan-glow: rgba(0,212,170,0.18);\n");
      out.write("            --gold:      #f0c040;\n");
      out.write("            --green:     #2ed573;\n");
      out.write("            --txt:       #edf2f7;\n");
      out.write("            --txt2:      #8892a4;\n");
      out.write("            --txt3:      #4a5568;\n");
      out.write("            --font: 'Outfit', sans-serif;\n");
      out.write("            --mono: 'JetBrains Mono', monospace;\n");
      out.write("            --ease: cubic-bezier(0.4,0,0.2,1);\n");
      out.write("            --spring: cubic-bezier(0.34,1.56,0.64,1);\n");
      out.write("        }\n");
      out.write("        *, *::before, *::after { box-sizing: border-box; margin:0; padding:0; }\n");
      out.write("        html { scroll-behavior:smooth; }\n");
      out.write("        body {\n");
      out.write("            font-family: var(--font);\n");
      out.write("            background: var(--bg);\n");
      out.write("            color: var(--txt);\n");
      out.write("            min-height:100vh;\n");
      out.write("            overflow-x:hidden;\n");
      out.write("            -webkit-font-smoothing:antialiased;\n");
      out.write("        }\n");
      out.write("        body::before {\n");
      out.write("            content:'';\n");
      out.write("            position:fixed; inset:0;\n");
      out.write("            background-image:\n");
      out.write("                linear-gradient(rgba(0,212,170,0.025) 1px, transparent 1px),\n");
      out.write("                linear-gradient(90deg, rgba(0,212,170,0.025) 1px, transparent 1px);\n");
      out.write("            background-size:64px 64px;\n");
      out.write("            pointer-events:none; z-index:0;\n");
      out.write("        }\n");
      out.write("        .orb {\n");
      out.write("            position:fixed; border-radius:50%;\n");
      out.write("            filter:blur(110px); pointer-events:none; z-index:0;\n");
      out.write("        }\n");
      out.write("        .orb1 {\n");
      out.write("            width:650px; height:650px;\n");
      out.write("            background:radial-gradient(circle, rgba(0,212,170,0.1) 0%, transparent 70%);\n");
      out.write("            top:-200px; right:-150px;\n");
      out.write("            animation:orbDrift 14s ease-in-out infinite;\n");
      out.write("        }\n");
      out.write("        .orb2 {\n");
      out.write("            width:500px; height:500px;\n");
      out.write("            background:radial-gradient(circle, rgba(99,102,241,0.09) 0%, transparent 70%);\n");
      out.write("            bottom:-100px; left:-100px;\n");
      out.write("            animation:orbDrift 18s ease-in-out infinite reverse;\n");
      out.write("        }\n");
      out.write("        a { text-decoration:none; color:inherit; }\n");
      out.write("        ::selection { background:rgba(0,212,170,0.25); color:var(--cyan); }\n");
      out.write("        ::-webkit-scrollbar { width:4px; }\n");
      out.write("        ::-webkit-scrollbar-track { background:var(--bg2); }\n");
      out.write("        ::-webkit-scrollbar-thumb { background:var(--cyan-dim); border-radius:99px; }\n");
      out.write("\n");
      out.write("        /* ── HEADER ── */\n");
      out.write("        header {\n");
      out.write("            position:fixed; top:0; left:0; right:0; z-index:1000;\n");
      out.write("            height:68px; padding:0 2.5rem;\n");
      out.write("            display:flex; align-items:center; justify-content:space-between;\n");
      out.write("            backdrop-filter:blur(24px) saturate(180%);\n");
      out.write("            -webkit-backdrop-filter:blur(24px) saturate(180%);\n");
      out.write("            background:rgba(8,12,20,0.8);\n");
      out.write("            border-bottom:1px solid var(--border);\n");
      out.write("            transition:all 0.3s var(--ease);\n");
      out.write("        }\n");
      out.write("        header.scrolled {\n");
      out.write("            border-bottom-color:var(--glow);\n");
      out.write("            box-shadow:0 2px 40px rgba(0,212,170,0.07);\n");
      out.write("        }\n");
      out.write("        .logo {\n");
      out.write("            font-size:1.6rem; font-weight:800;\n");
      out.write("            letter-spacing:-0.045em; display:flex; align-items:center;\n");
      out.write("        }\n");
      out.write("        .logo-a { color:var(--txt); }\n");
      out.write("        .logo-b {\n");
      out.write("            color:var(--cyan);\n");
      out.write("            background:linear-gradient(135deg, var(--cyan), #6366f1);\n");
      out.write("            -webkit-background-clip:text; -webkit-text-fill-color:transparent;\n");
      out.write("            background-clip:text;\n");
      out.write("        }\n");
      out.write("        .nav-links {\n");
      out.write("            display:flex; align-items:center; gap:0.4rem;\n");
      out.write("        }\n");
      out.write("        .nav-a {\n");
      out.write("            font-size:0.9rem; font-weight:500; color:var(--txt2);\n");
      out.write("            padding:0.45rem 1rem; border-radius:8px;\n");
      out.write("            transition:all 0.2s var(--ease);\n");
      out.write("        }\n");
      out.write("        .nav-a:hover { color:var(--txt); background:var(--surface2); }\n");
      out.write("        .btn-cta {\n");
      out.write("            font-family:var(--font); font-size:0.9rem; font-weight:700;\n");
      out.write("            color:var(--bg); background:var(--cyan);\n");
      out.write("            border:none; padding:0.5rem 1.4rem; border-radius:9px;\n");
      out.write("            cursor:pointer; transition:all 0.2s var(--spring);\n");
      out.write("            position:relative; overflow:hidden; display:inline-flex;\n");
      out.write("            align-items:center; gap:0.4rem;\n");
      out.write("        }\n");
      out.write("        .btn-cta:hover {\n");
      out.write("            transform:translateY(-2px);\n");
      out.write("            box-shadow:0 8px 28px rgba(0,212,170,0.45);\n");
      out.write("        }\n");
      out.write("        .btn-cta:active { transform:translateY(0); }\n");
      out.write("\n");
      out.write("        /* ── HERO ── */\n");
      out.write("        .wrap {\n");
      out.write("            max-width:1200px; margin:0 auto;\n");
      out.write("            padding:0 2rem; position:relative; z-index:1;\n");
      out.write("        }\n");
      out.write("        .hero {\n");
      out.write("            min-height:100vh; padding-top:68px;\n");
      out.write("            display:grid; grid-template-columns:1fr 1fr;\n");
      out.write("            align-items:center; gap:4rem;\n");
      out.write("        }\n");
      out.write("        .hero-left { padding:3.5rem 0; }\n");
      out.write("\n");
      out.write("        .hero-pill {\n");
      out.write("            display:inline-flex; align-items:center; gap:0.6rem;\n");
      out.write("            font-family:var(--mono); font-size:0.7rem; font-weight:500;\n");
      out.write("            color:var(--cyan);\n");
      out.write("            background:rgba(0,212,170,0.07);\n");
      out.write("            border:1px solid rgba(0,212,170,0.18);\n");
      out.write("            padding:0.4rem 1rem; border-radius:99px;\n");
      out.write("            margin-bottom:1.8rem;\n");
      out.write("            opacity:0; transform:translateY(16px);\n");
      out.write("            animation:up 0.6s 0.1s var(--ease) forwards;\n");
      out.write("        }\n");
      out.write("        .pill-dot {\n");
      out.write("            width:6px; height:6px; border-radius:50%;\n");
      out.write("            background:var(--cyan);\n");
      out.write("            animation:blink 2s ease-in-out infinite;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        h1.hero-h {\n");
      out.write("            font-size:clamp(2.8rem, 5.5vw, 4.8rem);\n");
      out.write("            font-weight:900; line-height:1.04;\n");
      out.write("            letter-spacing:-0.04em; margin-bottom:1.4rem;\n");
      out.write("            opacity:0; transform:translateY(24px);\n");
      out.write("            animation:up 0.7s 0.2s var(--ease) forwards;\n");
      out.write("        }\n");
      out.write("        .hl {\n");
      out.write("            display:inline-block;\n");
      out.write("            background:linear-gradient(135deg, var(--cyan) 0%, #6366f1 100%);\n");
      out.write("            -webkit-background-clip:text; -webkit-text-fill-color:transparent;\n");
      out.write("            background-clip:text;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero-sub {\n");
      out.write("            font-size:1.05rem; color:var(--txt2); line-height:1.75;\n");
      out.write("            max-width:480px; margin-bottom:2.2rem;\n");
      out.write("            opacity:0; transform:translateY(20px);\n");
      out.write("            animation:up 0.7s 0.3s var(--ease) forwards;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero-btns {\n");
      out.write("            display:flex; gap:1rem; margin-bottom:3rem;\n");
      out.write("            opacity:0; transform:translateY(20px);\n");
      out.write("            animation:up 0.7s 0.4s var(--ease) forwards;\n");
      out.write("        }\n");
      out.write("        .btn-big {\n");
      out.write("            font-family:var(--font); font-size:1rem; font-weight:700;\n");
      out.write("            color:var(--bg); background:var(--cyan);\n");
      out.write("            border:none; padding:0.9rem 2rem; border-radius:12px;\n");
      out.write("            cursor:pointer; transition:all 0.25s var(--spring);\n");
      out.write("            display:inline-flex; align-items:center; gap:0.5rem;\n");
      out.write("            position:relative; overflow:hidden;\n");
      out.write("        }\n");
      out.write("        .btn-big:hover {\n");
      out.write("            transform:translateY(-3px);\n");
      out.write("            box-shadow:0 14px 36px rgba(0,212,170,0.4);\n");
      out.write("        }\n");
      out.write("        .btn-big:active { transform:translateY(-1px); }\n");
      out.write("        .btn-big .ico { transition:transform 0.25s var(--spring); }\n");
      out.write("        .btn-big:hover .ico { transform:translateX(4px); }\n");
      out.write("\n");
      out.write("        .btn-ghost {\n");
      out.write("            font-family:var(--font); font-size:1rem; font-weight:600;\n");
      out.write("            color:var(--txt);\n");
      out.write("            background:transparent; border:1px solid var(--border);\n");
      out.write("            padding:0.9rem 1.8rem; border-radius:12px;\n");
      out.write("            cursor:pointer; transition:all 0.25s var(--ease);\n");
      out.write("            display:inline-flex; align-items:center; gap:0.5rem;\n");
      out.write("        }\n");
      out.write("        .btn-ghost:hover {\n");
      out.write("            border-color:var(--glow); color:var(--cyan);\n");
      out.write("            background:var(--cyan-bg); transform:translateY(-2px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Stats */\n");
      out.write("        .hero-stats {\n");
      out.write("            display:flex; gap:2rem;\n");
      out.write("            opacity:0; transform:translateY(20px);\n");
      out.write("            animation:up 0.7s 0.5s var(--ease) forwards;\n");
      out.write("        }\n");
      out.write("        .stat { display:flex; flex-direction:column; gap:0.2rem; }\n");
      out.write("        .stat-n {\n");
      out.write("            font-size:1.9rem; font-weight:900;\n");
      out.write("            letter-spacing:-0.04em; color:var(--txt); line-height:1;\n");
      out.write("        }\n");
      out.write("        .stat-n em { color:var(--cyan); font-style:normal; }\n");
      out.write("        .stat-l {\n");
      out.write("            font-size:0.72rem; font-weight:600; color:var(--txt3);\n");
      out.write("            letter-spacing:0.1em; text-transform:uppercase;\n");
      out.write("        }\n");
      out.write("        .stat-div { width:1px; background:var(--border); align-self:stretch; }\n");
      out.write("\n");
      out.write("        /* ── VISUAL ── */\n");
      out.write("        .hero-right {\n");
      out.write("            display:flex; justify-content:center; align-items:center;\n");
      out.write("            opacity:0; animation:scaleIn 0.9s 0.35s var(--spring) forwards;\n");
      out.write("        }\n");
      out.write("        .card-scene { position:relative; width:380px; height:430px; }\n");
      out.write("\n");
      out.write("        .bank-card {\n");
      out.write("            position:absolute; border-radius:24px; padding:1.8rem; width:320px;\n");
      out.write("        }\n");
      out.write("        .card-primary {\n");
      out.write("            background:linear-gradient(135deg, #0c1628 0%, #0d1f3c 60%, #0a1628 100%);\n");
      out.write("            border:1px solid rgba(0,212,170,0.22);\n");
      out.write("            box-shadow:0 24px 60px rgba(0,0,0,0.65), 0 0 0 1px rgba(0,212,170,0.08);\n");
      out.write("            top:40px; left:25px; z-index:3;\n");
      out.write("            animation:cardBob 7s ease-in-out infinite;\n");
      out.write("            cursor:pointer;\n");
      out.write("            transition:box-shadow 0.3s;\n");
      out.write("        }\n");
      out.write("        .card-primary:hover { box-shadow:0 28px 70px rgba(0,0,0,0.7), 0 0 30px rgba(0,212,170,0.15); }\n");
      out.write("        .card-b1 {\n");
      out.write("            background:linear-gradient(135deg, rgba(0,212,170,0.12), rgba(0,212,170,0.04));\n");
      out.write("            border:1px solid rgba(0,212,170,0.1);\n");
      out.write("            top:5px; left:55px; z-index:2;\n");
      out.write("            transform:rotate(6deg); width:300px; height:180px;\n");
      out.write("            animation:cardBob 7s 0.6s ease-in-out infinite;\n");
      out.write("        }\n");
      out.write("        .card-b2 {\n");
      out.write("            background:linear-gradient(135deg, rgba(99,102,241,0.1), rgba(99,102,241,0.03));\n");
      out.write("            border:1px solid rgba(99,102,241,0.1);\n");
      out.write("            top:0; left:5px; z-index:1;\n");
      out.write("            transform:rotate(-5deg); width:300px; height:180px;\n");
      out.write("            animation:cardBob 7s 1.2s ease-in-out infinite;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .chip {\n");
      out.write("            width:46px; height:35px;\n");
      out.write("            background:linear-gradient(135deg, var(--gold) 0%, #c8961c 100%);\n");
      out.write("            border-radius:7px; margin-bottom:1.6rem;\n");
      out.write("            position:relative; overflow:hidden;\n");
      out.write("        }\n");
      out.write("        .chip::after {\n");
      out.write("            content:''; position:absolute; inset:4px;\n");
      out.write("            border:1px solid rgba(0,0,0,0.2); border-radius:3px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-num {\n");
      out.write("            font-family:var(--mono); font-size:0.88rem;\n");
      out.write("            color:rgba(255,255,255,0.55); letter-spacing:0.18em;\n");
      out.write("            margin-bottom:1.4rem;\n");
      out.write("        }\n");
      out.write("        .card-foot { display:flex; justify-content:space-between; align-items:flex-end; }\n");
      out.write("        .card-holder { font-size:0.75rem; color:rgba(255,255,255,0.4); text-transform:uppercase; letter-spacing:0.1em; }\n");
      out.write("        .card-logo-text { font-size:1.4rem; font-weight:900; color:var(--cyan); letter-spacing:-0.03em; }\n");
      out.write("\n");
      out.write("        /* Floating info chips */\n");
      out.write("        .chip-float {\n");
      out.write("            position:absolute; z-index:5;\n");
      out.write("            background:rgba(13,18,32,0.9);\n");
      out.write("            border:1px solid var(--border);\n");
      out.write("            border-radius:14px; padding:0.8rem 1rem;\n");
      out.write("            display:flex; align-items:center; gap:0.7rem;\n");
      out.write("            backdrop-filter:blur(16px);\n");
      out.write("            box-shadow:0 8px 32px rgba(0,0,0,0.5);\n");
      out.write("        }\n");
      out.write("        .cf1 { bottom:20px; left:-40px; animation:chipBob 5s 1s ease-in-out infinite; }\n");
      out.write("        .cf2 { top:10px; right:-30px; animation:chipBob 5s 2s ease-in-out infinite reverse; }\n");
      out.write("        .cf-ico {\n");
      out.write("            width:34px; height:34px; border-radius:10px;\n");
      out.write("            display:flex; align-items:center; justify-content:center; font-size:1rem;\n");
      out.write("        }\n");
      out.write("        .ci-g { background:rgba(46,213,115,0.15); }\n");
      out.write("        .ci-c { background:rgba(0,212,170,0.15); }\n");
      out.write("        .cf-lbl { font-size:0.68rem; color:var(--txt3); }\n");
      out.write("        .cf-val { font-size:0.9rem; font-weight:700; }\n");
      out.write("        .cv-g { color:var(--green); }\n");
      out.write("        .cv-c { color:var(--cyan); }\n");
      out.write("\n");
      out.write("        /* ── FEATURES ── */\n");
      out.write("        .features {\n");
      out.write("            padding:7rem 0; position:relative; z-index:1;\n");
      out.write("        }\n");
      out.write("        .section-eyebrow {\n");
      out.write("            display:flex; align-items:center; gap:0.7rem;\n");
      out.write("            font-family:var(--mono); font-size:0.7rem; font-weight:500;\n");
      out.write("            color:var(--cyan); letter-spacing:0.15em; text-transform:uppercase;\n");
      out.write("            margin-bottom:1rem;\n");
      out.write("        }\n");
      out.write("        .section-eyebrow::before {\n");
      out.write("            content:''; width:20px; height:2px;\n");
      out.write("            background:var(--cyan); border-radius:99px;\n");
      out.write("        }\n");
      out.write("        h2.sec-h {\n");
      out.write("            font-size:clamp(1.9rem, 3.5vw, 2.8rem);\n");
      out.write("            font-weight:900; letter-spacing:-0.04em;\n");
      out.write("            margin-bottom:0.7rem; line-height:1.1;\n");
      out.write("        }\n");
      out.write("        .sec-sub {\n");
      out.write("            font-size:1rem; color:var(--txt2); line-height:1.7;\n");
      out.write("            max-width:480px; margin-bottom:3rem;\n");
      out.write("        }\n");
      out.write("        .feat-grid {\n");
      out.write("            display:grid; grid-template-columns:repeat(3,1fr); gap:1.4rem;\n");
      out.write("        }\n");
      out.write("        .feat-card {\n");
      out.write("            background:var(--surface); border:1px solid var(--border);\n");
      out.write("            border-radius:20px; padding:1.8rem;\n");
      out.write("            transition:all 0.3s var(--ease); cursor:default;\n");
      out.write("            position:relative; overflow:hidden;\n");
      out.write("        }\n");
      out.write("        .feat-card::before {\n");
      out.write("            content:''; position:absolute; inset:0;\n");
      out.write("            background:linear-gradient(135deg, var(--cyan-glow), transparent 60%);\n");
      out.write("            opacity:0; transition:opacity 0.3s;\n");
      out.write("        }\n");
      out.write("        .feat-card:hover {\n");
      out.write("            border-color:var(--glow); transform:translateY(-5px);\n");
      out.write("            box-shadow:0 20px 50px rgba(0,212,170,0.1);\n");
      out.write("        }\n");
      out.write("        .feat-card:hover::before { opacity:1; }\n");
      out.write("        .feat-ico {\n");
      out.write("            width:50px; height:50px; border-radius:14px;\n");
      out.write("            background:rgba(0,212,170,0.1); border:1px solid rgba(0,212,170,0.18);\n");
      out.write("            display:flex; align-items:center; justify-content:center;\n");
      out.write("            font-size:1.3rem; margin-bottom:1.2rem;\n");
      out.write("            position:relative; z-index:1;\n");
      out.write("        }\n");
      out.write("        .feat-t {\n");
      out.write("            font-size:1rem; font-weight:700; margin-bottom:0.45rem;\n");
      out.write("            letter-spacing:-0.01em; position:relative; z-index:1;\n");
      out.write("        }\n");
      out.write("        .feat-d { font-size:0.86rem; color:var(--txt2); line-height:1.65; position:relative; z-index:1; }\n");
      out.write("\n");
      out.write("        /* ── CTA BOX ── */\n");
      out.write("        .cta-wrap { padding-bottom:5rem; position:relative; z-index:1; }\n");
      out.write("        .cta-inner {\n");
      out.write("            background:linear-gradient(135deg, rgba(0,212,170,0.08), rgba(99,102,241,0.06));\n");
      out.write("            border:1px solid rgba(0,212,170,0.18);\n");
      out.write("            border-radius:28px; padding:4rem;\n");
      out.write("            text-align:center; position:relative; overflow:hidden;\n");
      out.write("        }\n");
      out.write("        .cta-inner::before {\n");
      out.write("            content:''; position:absolute;\n");
      out.write("            top:-120px; left:50%; transform:translateX(-50%);\n");
      out.write("            width:500px; height:500px;\n");
      out.write("            background:radial-gradient(circle, rgba(0,212,170,0.1), transparent 70%);\n");
      out.write("            pointer-events:none;\n");
      out.write("        }\n");
      out.write("        .cta-inner h2 {\n");
      out.write("            font-size:clamp(2rem,4.5vw,3.2rem); font-weight:900;\n");
      out.write("            letter-spacing:-0.04em; margin-bottom:1rem; position:relative; z-index:1;\n");
      out.write("        }\n");
      out.write("        .cta-inner p { font-size:1rem; color:var(--txt2); margin-bottom:2rem; position:relative; z-index:1; }\n");
      out.write("\n");
      out.write("        /* ── ANIMATIONS ── */\n");
      out.write("        @keyframes up { to { opacity:1; transform:translateY(0); } }\n");
      out.write("        @keyframes scaleIn { from { opacity:0; transform:scale(0.88); } to { opacity:1; transform:scale(1); } }\n");
      out.write("        @keyframes orbDrift {\n");
      out.write("            0%,100% { transform:translate(0,0); }\n");
      out.write("            33% { transform:translate(40px,-25px); }\n");
      out.write("            66% { transform:translate(-20px,30px); }\n");
      out.write("        }\n");
      out.write("        @keyframes cardBob {\n");
      out.write("            0%,100% { transform:translateY(0); }\n");
      out.write("            50% { transform:translateY(-16px); }\n");
      out.write("        }\n");
      out.write("        @keyframes chipBob {\n");
      out.write("            0%,100% { transform:translateY(0); }\n");
      out.write("            50% { transform:translateY(-9px); }\n");
      out.write("        }\n");
      out.write("        @keyframes blink {\n");
      out.write("            0%,100% { opacity:1; transform:scale(1); }\n");
      out.write("            50% { opacity:0.4; transform:scale(0.75); }\n");
      out.write("        }\n");
      out.write("        @keyframes rippleOut { to { transform:scale(1); opacity:0; } }\n");
      out.write("\n");
      out.write("        @media (max-width:900px) {\n");
      out.write("            .hero { grid-template-columns:1fr; min-height:auto; padding:6rem 0 4rem; gap:3rem; }\n");
      out.write("            .hero-right { order:-1; }\n");
      out.write("            .card-scene { transform:scale(0.85); }\n");
      out.write("            .feat-grid { grid-template-columns:1fr 1fr; }\n");
      out.write("        }\n");
      out.write("        @media (max-width:600px) {\n");
      out.write("            header { padding:0 1rem; }\n");
      out.write("            .wrap { padding:0 1rem; }\n");
      out.write("            .hero-btns { flex-direction:column; }\n");
      out.write("            .feat-grid { grid-template-columns:1fr; }\n");
      out.write("            .cta-inner { padding:2.5rem 1.5rem; }\n");
      out.write("            .card-scene { transform:scale(0.72); transform-origin:center top; }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"orb orb1\"></div>\n");
      out.write("<div class=\"orb orb2\"></div>\n");
      out.write("\n");
      out.write("<!-- ══ HEADER ══ -->\n");
      out.write("<header id=\"hdr\">\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" class=\"logo\">\n");
      out.write("        <span class=\"logo-a\">Ace</span><span class=\"logo-b\">Bank</span>\n");
      out.write("    </a>\n");
      out.write("    <div class=\"nav-links\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp\" class=\"nav-a\">Login</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sign-up.jsp\" class=\"btn-cta\">\n");
      out.write("            Get Started\n");
      out.write("            <svg width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"><path d=\"M5 12h14M12 5l7 7-7 7\"/></svg>\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<div class=\"wrap\">\n");
      out.write("\n");
      out.write("<!-- ══ HERO ══ -->\n");
      out.write("<section class=\"hero\">\n");
      out.write("    <div class=\"hero-left\">\n");
      out.write("        <div class=\"hero-pill\">\n");
      out.write("            <span class=\"pill-dot\"></span>\n");
      out.write("            Trusted by 2M+ users worldwide\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <h1 class=\"hero-h\">\n");
      out.write("            Banking Made<br>\n");
      out.write("            <span class=\"hl\">Easy</span> &amp; Smart\n");
      out.write("        </h1>\n");
      out.write("\n");
      out.write("        <p class=\"hero-sub\">\n");
      out.write("            Join over 40,000 people who open an AceBank account every week.\n");
      out.write("            Manage, spend, and grow your money with zero friction.\n");
      out.write("        </p>\n");
      out.write("\n");
      out.write("        <div class=\"hero-btns\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sign-up.jsp\" class=\"btn-big\">\n");
      out.write("                Open Free Account\n");
      out.write("                <svg class=\"ico\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"><path d=\"M5 12h14M12 5l7 7-7 7\"/></svg>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"#features\" class=\"btn-ghost\">\n");
      out.write("                View Features\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"hero-stats\">\n");
      out.write("            <div class=\"stat\">\n");
      out.write("                <div class=\"stat-n\"><span class=\"cnt\" data-to=\"2\">0</span>M<em>+</em></div>\n");
      out.write("                <div class=\"stat-l\">Active Users</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"stat-div\"></div>\n");
      out.write("            <div class=\"stat\">\n");
      out.write("                <div class=\"stat-n\">₹<span class=\"cnt\" data-to=\"50\">0</span>B<em>+</em></div>\n");
      out.write("                <div class=\"stat-l\">Transferred</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"stat-div\"></div>\n");
      out.write("            <div class=\"stat\">\n");
      out.write("                <div class=\"stat-n\"><span class=\"cnt\" data-to=\"99\">0</span><em>.9%</em></div>\n");
      out.write("                <div class=\"stat-l\">Uptime</div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"hero-right\">\n");
      out.write("        <div class=\"card-scene\">\n");
      out.write("            <div class=\"bank-card card-b2\"></div>\n");
      out.write("            <div class=\"bank-card card-b1\"></div>\n");
      out.write("            <div class=\"bank-card card-primary\" id=\"tiltCard\">\n");
      out.write("                <div class=\"chip\"></div>\n");
      out.write("                <div class=\"card-num\">4521 •••• •••• 8834</div>\n");
      out.write("                <div class=\"card-foot\">\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"card-holder\">Premium Account</div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-logo-text\">Ace</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"chip-float cf1\">\n");
      out.write("                <div class=\"cf-ico ci-g\">💰</div>\n");
      out.write("                <div>\n");
      out.write("                    <div class=\"cf-lbl\">Last Deposit</div>\n");
      out.write("                    <div class=\"cf-val cv-g\">+₹24,500</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"chip-float cf2\">\n");
      out.write("                <div class=\"cf-ico ci-c\">⚡</div>\n");
      out.write("                <div>\n");
      out.write("                    <div class=\"cf-lbl\">Instant Transfer</div>\n");
      out.write("                    <div class=\"cf-val cv-c\">0 Fees</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- ══ FEATURES ══ -->\n");
      out.write("<section class=\"features\" id=\"features\">\n");
      out.write("    <div class=\"section-eyebrow\">Why AceBank</div>\n");
      out.write("    <h2 class=\"sec-h\">Everything you need,<br>nothing you don't.</h2>\n");
      out.write("    <p class=\"sec-sub\">Built for speed, security, and simplicity — every feature is designed to make your financial life frictionless.</p>\n");
      out.write("\n");
      out.write("    <div class=\"feat-grid\">\n");
      out.write("        <div class=\"feat-card rc\">\n");
      out.write("            <div class=\"feat-ico\">🔐</div>\n");
      out.write("            <div class=\"feat-t\">Bank-Grade Security</div>\n");
      out.write("            <p class=\"feat-d\">256-bit AES encryption, biometric auth, and real-time fraud detection keep your money safe.</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"feat-card rc\">\n");
      out.write("            <div class=\"feat-ico\">⚡</div>\n");
      out.write("            <div class=\"feat-t\">Instant Transfers</div>\n");
      out.write("            <p class=\"feat-d\">Send money to anyone in seconds with zero hidden fees — domestic or international.</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"feat-card rc\">\n");
      out.write("            <div class=\"feat-ico\">📊</div>\n");
      out.write("            <div class=\"feat-t\">Smart Analytics</div>\n");
      out.write("            <p class=\"feat-d\">Real-time spending insights, budgets, and reports so you always know where every rupee goes.</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"feat-card rc\">\n");
      out.write("            <div class=\"feat-ico\">🌐</div>\n");
      out.write("            <div class=\"feat-t\">24/7 Availability</div>\n");
      out.write("            <p class=\"feat-d\">Your bank never sleeps. Access your account anytime, from anywhere in the world.</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"feat-card rc\">\n");
      out.write("            <div class=\"feat-ico\">💳</div>\n");
      out.write("            <div class=\"feat-t\">Virtual Cards</div>\n");
      out.write("            <p class=\"feat-d\">Create instant virtual cards for online shopping. Freeze or delete at any time.</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"feat-card rc\">\n");
      out.write("            <div class=\"feat-ico\">🤝</div>\n");
      out.write("            <div class=\"feat-t\">Zero Fees</div>\n");
      out.write("            <p class=\"feat-d\">No maintenance fees, no minimum balance, no surprise charges — ever.</p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- ══ CTA ══ -->\n");
      out.write("<div class=\"cta-wrap\">\n");
      out.write("    <div class=\"cta-inner\">\n");
      out.write("        <h2>Ready to get started?</h2>\n");
      out.write("        <p>Open your account in under 3 minutes. No paperwork. No branch visits.</p>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sign-up.jsp\" class=\"btn-big\" style=\"display:inline-flex; font-size:1rem; padding:1rem 2.5rem;\">\n");
      out.write("            Create Free Account\n");
      out.write("            <svg class=\"ico\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"><path d=\"M5 12h14M12 5l7 7-7 7\"/></svg>\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div><!-- /wrap -->\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("// ── Scroll header ──\n");
      out.write("const hdr = document.getElementById('hdr');\n");
      out.write("addEventListener('scroll', () => hdr.classList.toggle('scrolled', scrollY > 20), {passive:true});\n");
      out.write("\n");
      out.write("// ── 3D card tilt ──\n");
      out.write("const tc = document.getElementById('tiltCard');\n");
      out.write("tc && tc.addEventListener('mousemove', e => {\n");
      out.write("    const r = tc.getBoundingClientRect();\n");
      out.write("    const x = (e.clientX - r.left) / r.width - 0.5;\n");
      out.write("    const y = (e.clientY - r.top) / r.height - 0.5;\n");
      out.write("    tc.style.transform = `perspective(900px) rotateY(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${x*20}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("deg) rotateX(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${-y*15}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("deg)`;\n");
      out.write("});\n");
      out.write("tc && tc.addEventListener('mouseleave', () => tc.style.transform = '');\n");
      out.write("\n");
      out.write("// ── Counter animation ──\n");
      out.write("const countIO = new IntersectionObserver(entries => {\n");
      out.write("    entries.forEach(e => {\n");
      out.write("        if (!e.isIntersecting) return;\n");
      out.write("        const el = e.target, target = +el.dataset.to;\n");
      out.write("        let start = null;\n");
      out.write("        const tick = ts => {\n");
      out.write("            if (!start) start = ts;\n");
      out.write("            const p = Math.min((ts-start)/1600, 1);\n");
      out.write("            el.textContent = Math.floor((1-Math.pow(1-p,4))*target);\n");
      out.write("            if (p < 1) requestAnimationFrame(tick);\n");
      out.write("        };\n");
      out.write("        requestAnimationFrame(tick);\n");
      out.write("        countIO.unobserve(el);\n");
      out.write("    });\n");
      out.write("}, {threshold:0.4});\n");
      out.write("document.querySelectorAll('.cnt').forEach(el => countIO.observe(el));\n");
      out.write("\n");
      out.write("// ── Scroll reveal ──\n");
      out.write("const revIO = new IntersectionObserver(entries => {\n");
      out.write("    entries.forEach((e, i) => {\n");
      out.write("        if (!e.isIntersecting) return;\n");
      out.write("        setTimeout(() => {\n");
      out.write("            e.target.style.opacity = '1';\n");
      out.write("            e.target.style.transform = 'translateY(0)';\n");
      out.write("        }, i * 90);\n");
      out.write("        revIO.unobserve(e.target);\n");
      out.write("    });\n");
      out.write("}, {threshold:0.1});\n");
      out.write("document.querySelectorAll('.rc').forEach(el => {\n");
      out.write("    el.style.cssText += 'opacity:0;transform:translateY(28px);transition:opacity 0.6s ease,transform 0.6s ease;';\n");
      out.write("    revIO.observe(el);\n");
      out.write("});\n");
      out.write("\n");
      out.write("// ── Ripple effect ──\n");
      out.write("document.querySelectorAll('.btn-big,.btn-ghost,.btn-cta').forEach(btn => {\n");
      out.write("    btn.addEventListener('click', function(e) {\n");
      out.write("        const r = this.getBoundingClientRect();\n");
      out.write("        const size = Math.max(r.width, r.height)*2;\n");
      out.write("        const ripple = document.createElement('span');\n");
      out.write("        ripple.style.cssText = `position:absolute;border-radius:50%;pointer-events:none;\n");
      out.write("            width:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${size}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("px;height:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${size}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("px;\n");
      out.write("            left:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.clientX-r.left-size/2}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("px;top:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.clientY-r.top-size/2}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("px;\n");
      out.write("            background:rgba(255,255,255,0.18);transform:scale(0);\n");
      out.write("            animation:rippleOut 0.65s ease-out forwards;`;\n");
      out.write("        this.style.cssText += ';position:relative;overflow:hidden;';\n");
      out.write("        this.appendChild(ripple);\n");
      out.write("        setTimeout(() => ripple.remove(), 700);\n");
      out.write("    });\n");
      out.write("});\n");
      out.write("const rs = document.createElement('style');\n");
      out.write("rs.textContent = '@keyframes rippleOut{to{transform:scale(1);opacity:0;}}';\n");
      out.write("document.head.appendChild(rs);\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
