/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-02-27 05:20:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/anubh/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664433678000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1771486511008L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    String savedAccount = "";
    Cookie[] cookies = request.getCookies();
    if (cookies != null) {
        for (Cookie c : cookies) {
            if ("rememberedAccount".equals(c.getName())) {
                savedAccount = c.getValue();
                pageContext.setAttribute("savedAccount", savedAccount);
            }
        }
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Login | AceBank</title>\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --bg:       #080c14;\n");
      out.write("            --bg2:      #0d1220;\n");
      out.write("            --bg3:      #111827;\n");
      out.write("            --surface:  rgba(255,255,255,0.04);\n");
      out.write("            --surface2: rgba(255,255,255,0.07);\n");
      out.write("            --border:   rgba(255,255,255,0.08);\n");
      out.write("            --glow:     rgba(0,212,170,0.3);\n");
      out.write("            --cyan:     #00d4aa;\n");
      out.write("            --cyan-dim: #00a882;\n");
      out.write("            --cyan-bg:  rgba(0,212,170,0.08);\n");
      out.write("            --red:      #ff4757;\n");
      out.write("            --green:    #2ed573;\n");
      out.write("            --gold:     #f0c040;\n");
      out.write("            --txt:      #edf2f7;\n");
      out.write("            --txt2:     #8892a4;\n");
      out.write("            --txt3:     #4a5568;\n");
      out.write("            --font: 'Outfit', sans-serif;\n");
      out.write("            --mono: 'JetBrains Mono', monospace;\n");
      out.write("            --ease: cubic-bezier(0.4,0,0.2,1);\n");
      out.write("            --spring: cubic-bezier(0.34,1.56,0.64,1);\n");
      out.write("        }\n");
      out.write("        *,*::before,*::after { box-sizing:border-box; margin:0; padding:0; }\n");
      out.write("        html { scroll-behavior:smooth; }\n");
      out.write("        body {\n");
      out.write("            font-family:var(--font); background:var(--bg);\n");
      out.write("            color:var(--txt); min-height:100vh;\n");
      out.write("            overflow-x:hidden; -webkit-font-smoothing:antialiased;\n");
      out.write("            display:flex; flex-direction:column;\n");
      out.write("        }\n");
      out.write("        body::before {\n");
      out.write("            content:''; position:fixed; inset:0;\n");
      out.write("            background-image:\n");
      out.write("                linear-gradient(rgba(0,212,170,0.025) 1px, transparent 1px),\n");
      out.write("                linear-gradient(90deg, rgba(0,212,170,0.025) 1px, transparent 1px);\n");
      out.write("            background-size:64px 64px;\n");
      out.write("            pointer-events:none; z-index:0;\n");
      out.write("        }\n");
      out.write("        .orb {\n");
      out.write("            position:fixed; border-radius:50%;\n");
      out.write("            filter:blur(100px); pointer-events:none; z-index:0;\n");
      out.write("        }\n");
      out.write("        .orb1 {\n");
      out.write("            width:500px; height:500px;\n");
      out.write("            background:radial-gradient(circle, rgba(0,212,170,0.12) 0%, transparent 70%);\n");
      out.write("            top:-150px; right:-100px;\n");
      out.write("        }\n");
      out.write("        .orb2 {\n");
      out.write("            width:400px; height:400px;\n");
      out.write("            background:radial-gradient(circle, rgba(99,102,241,0.1) 0%, transparent 70%);\n");
      out.write("            bottom:-100px; left:-100px;\n");
      out.write("        }\n");
      out.write("        a { text-decoration:none; color:inherit; }\n");
      out.write("        ::selection { background:rgba(0,212,170,0.2); color:var(--cyan); }\n");
      out.write("        ::-webkit-scrollbar { width:4px; }\n");
      out.write("        ::-webkit-scrollbar-track { background:var(--bg2); }\n");
      out.write("        ::-webkit-scrollbar-thumb { background:var(--cyan-dim); border-radius:99px; }\n");
      out.write("\n");
      out.write("        /* ── HEADER ── */\n");
      out.write("        header {\n");
      out.write("            position:relative; z-index:100;\n");
      out.write("            height:68px; padding:0 2.5rem;\n");
      out.write("            display:flex; align-items:center; justify-content:space-between;\n");
      out.write("            backdrop-filter:blur(20px);\n");
      out.write("            background:rgba(8,12,20,0.75);\n");
      out.write("            border-bottom:1px solid var(--border);\n");
      out.write("        }\n");
      out.write("        .logo {\n");
      out.write("            font-size:1.55rem; font-weight:800; letter-spacing:-0.045em;\n");
      out.write("            display:flex; align-items:center;\n");
      out.write("        }\n");
      out.write("        .logo-a { color:var(--txt); }\n");
      out.write("        .logo-b {\n");
      out.write("            background:linear-gradient(135deg,var(--cyan),#6366f1);\n");
      out.write("            -webkit-background-clip:text; -webkit-text-fill-color:transparent;\n");
      out.write("            background-clip:text;\n");
      out.write("        }\n");
      out.write("        .hdr-links { display:flex; align-items:center; gap:0.4rem; }\n");
      out.write("        .nav-a {\n");
      out.write("            font-size:0.88rem; font-weight:500; color:var(--txt2);\n");
      out.write("            padding:0.4rem 0.9rem; border-radius:8px;\n");
      out.write("            transition:all 0.2s var(--ease);\n");
      out.write("        }\n");
      out.write("        .nav-a:hover { color:var(--txt); background:var(--surface2); }\n");
      out.write("        .btn-nav {\n");
      out.write("            font-family:var(--font); font-size:0.88rem; font-weight:700;\n");
      out.write("            color:var(--bg); background:var(--cyan);\n");
      out.write("            border:none; padding:0.4rem 1.2rem; border-radius:8px;\n");
      out.write("            cursor:pointer; transition:all 0.2s var(--spring);\n");
      out.write("        }\n");
      out.write("        .btn-nav:hover { transform:translateY(-2px); box-shadow:0 6px 20px rgba(0,212,170,0.4); }\n");
      out.write("\n");
      out.write("        /* ── MAIN LAYOUT ── */\n");
      out.write("        .auth-page {\n");
      out.write("            flex:1; display:grid; grid-template-columns:1fr 1fr;\n");
      out.write("            min-height:calc(100vh - 68px); position:relative; z-index:1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Left decorative panel */\n");
      out.write("        .auth-left {\n");
      out.write("            background:linear-gradient(160deg, rgba(0,212,170,0.06) 0%, transparent 50%);\n");
      out.write("            border-right:1px solid var(--border);\n");
      out.write("            display:flex; flex-direction:column;\n");
      out.write("            align-items:center; justify-content:center;\n");
      out.write("            padding:3rem; gap:3rem;\n");
      out.write("        }\n");
      out.write("        .auth-left-inner { max-width:380px; width:100%; }\n");
      out.write("        .brand-title {\n");
      out.write("            font-size:2.4rem; font-weight:900;\n");
      out.write("            letter-spacing:-0.04em; margin-bottom:1rem; line-height:1.1;\n");
      out.write("        }\n");
      out.write("        .brand-title span {\n");
      out.write("            background:linear-gradient(135deg,var(--cyan),#6366f1);\n");
      out.write("            -webkit-background-clip:text; -webkit-text-fill-color:transparent;\n");
      out.write("            background-clip:text;\n");
      out.write("        }\n");
      out.write("        .brand-sub { font-size:0.95rem; color:var(--txt2); line-height:1.7; margin-bottom:2.5rem; }\n");
      out.write("\n");
      out.write("        /* Feature list */\n");
      out.write("        .feat-list { display:flex; flex-direction:column; gap:0.9rem; }\n");
      out.write("        .feat-item {\n");
      out.write("            display:flex; align-items:center; gap:1rem;\n");
      out.write("            padding:1rem 1.2rem;\n");
      out.write("            background:var(--surface); border:1px solid var(--border);\n");
      out.write("            border-radius:12px; transition:all 0.25s var(--ease);\n");
      out.write("        }\n");
      out.write("        .feat-item:hover { border-color:var(--glow); background:var(--surface2); }\n");
      out.write("        .feat-ico-wrap {\n");
      out.write("            width:38px; height:38px; border-radius:10px;\n");
      out.write("            background:rgba(0,212,170,0.1); border:1px solid rgba(0,212,170,0.15);\n");
      out.write("            display:flex; align-items:center; justify-content:center;\n");
      out.write("            font-size:1rem; flex-shrink:0;\n");
      out.write("        }\n");
      out.write("        .feat-txt { font-size:0.86rem; font-weight:500; color:var(--txt2); }\n");
      out.write("        .feat-txt strong { display:block; font-size:0.92rem; color:var(--txt); margin-bottom:0.1rem; }\n");
      out.write("\n");
      out.write("        /* ── AUTH CARD ── */\n");
      out.write("        .auth-right {\n");
      out.write("            display:flex; align-items:center; justify-content:center;\n");
      out.write("            padding:2.5rem;\n");
      out.write("        }\n");
      out.write("        .auth-card {\n");
      out.write("            width:100%; max-width:420px;\n");
      out.write("            background:rgba(13,18,32,0.8);\n");
      out.write("            border:1px solid var(--border);\n");
      out.write("            border-radius:24px; padding:2.8rem;\n");
      out.write("            backdrop-filter:blur(16px);\n");
      out.write("            position:relative; overflow:hidden;\n");
      out.write("            box-shadow:0 24px 80px rgba(0,0,0,0.6);\n");
      out.write("            animation:slideUp 0.6s 0.1s var(--spring) both;\n");
      out.write("        }\n");
      out.write("        .auth-card::before {\n");
      out.write("            content:''; position:absolute;\n");
      out.write("            top:0; left:0; right:0; height:1px;\n");
      out.write("            background:linear-gradient(90deg, transparent 0%, var(--cyan) 50%, transparent 100%);\n");
      out.write("            opacity:0.5;\n");
      out.write("        }\n");
      out.write("        .auth-card::after {\n");
      out.write("            content:''; position:absolute;\n");
      out.write("            inset:0;\n");
      out.write("            background:radial-gradient(ellipse 80% 40% at 50% 0%, rgba(0,212,170,0.06), transparent 60%);\n");
      out.write("            pointer-events:none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-icon {\n");
      out.write("            width:56px; height:56px; border-radius:16px;\n");
      out.write("            background:rgba(0,212,170,0.1);\n");
      out.write("            border:1px solid rgba(0,212,170,0.2);\n");
      out.write("            display:flex; align-items:center; justify-content:center;\n");
      out.write("            font-size:1.5rem; margin-bottom:1.5rem;\n");
      out.write("            position:relative; z-index:1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-h {\n");
      out.write("            font-size:1.75rem; font-weight:800; letter-spacing:-0.03em;\n");
      out.write("            margin-bottom:0.4rem; position:relative; z-index:1;\n");
      out.write("        }\n");
      out.write("        .card-sub {\n");
      out.write("            font-size:0.9rem; color:var(--txt2); margin-bottom:2rem;\n");
      out.write("            position:relative; z-index:1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* ── FORM ── */\n");
      out.write("        .form { display:flex; flex-direction:column; gap:1.2rem; position:relative; z-index:1; }\n");
      out.write("\n");
      out.write("        .field { display:flex; flex-direction:column; gap:0.45rem; }\n");
      out.write("\n");
      out.write("        label {\n");
      out.write("            font-size:0.75rem; font-weight:600; color:var(--txt2);\n");
      out.write("            letter-spacing:0.07em; text-transform:uppercase;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .input-wrap { position:relative; }\n");
      out.write("\n");
      out.write("        .input-ico {\n");
      out.write("            position:absolute; left:1rem; top:50%; transform:translateY(-50%);\n");
      out.write("            color:var(--txt3); font-size:1rem; pointer-events:none;\n");
      out.write("            transition:color 0.2s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input[type=\"text\"],\n");
      out.write("        input[type=\"password\"],\n");
      out.write("        input[type=\"email\"],\n");
      out.write("        input[type=\"number\"] {\n");
      out.write("            width:100%;\n");
      out.write("            background:rgba(255,255,255,0.04);\n");
      out.write("            border:1px solid var(--border);\n");
      out.write("            border-radius:10px;\n");
      out.write("            padding:0.8rem 1rem 0.8rem 2.8rem;\n");
      out.write("            font-family:var(--font); font-size:0.95rem;\n");
      out.write("            color:var(--txt); outline:none;\n");
      out.write("            transition:all 0.25s var(--ease);\n");
      out.write("        }\n");
      out.write("        input::placeholder { color:var(--txt3); }\n");
      out.write("        input:focus {\n");
      out.write("            border-color:var(--cyan);\n");
      out.write("            background:rgba(0,212,170,0.05);\n");
      out.write("            box-shadow:0 0 0 3px rgba(0,212,170,0.12);\n");
      out.write("        }\n");
      out.write("        input:focus + .input-ico,\n");
      out.write("        .input-wrap:focus-within .input-ico { color:var(--cyan); }\n");
      out.write("        input.err {\n");
      out.write("            border-color:var(--red);\n");
      out.write("            background:rgba(255,71,87,0.05);\n");
      out.write("            box-shadow:0 0 0 3px rgba(255,71,87,0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Eye toggle */\n");
      out.write("        .eye-btn {\n");
      out.write("            position:absolute; right:1rem; top:50%; transform:translateY(-50%);\n");
      out.write("            background:none; border:none; color:var(--txt3);\n");
      out.write("            cursor:pointer; font-size:1.1rem; padding:0;\n");
      out.write("            transition:color 0.2s; line-height:1;\n");
      out.write("        }\n");
      out.write("        .eye-btn:hover { color:var(--txt2); }\n");
      out.write("\n");
      out.write("        .field-err {\n");
      out.write("            font-size:0.76rem; color:var(--red); margin-top:0.2rem;\n");
      out.write("            display:none; align-items:center; gap:0.35rem;\n");
      out.write("        }\n");
      out.write("        .field-err.show { display:flex; animation:errPop 0.2s var(--spring); }\n");
      out.write("\n");
      out.write("        /* Checkbox row */\n");
      out.write("        .check-row {\n");
      out.write("            display:flex; align-items:center; justify-content:space-between; gap:1rem;\n");
      out.write("        }\n");
      out.write("        .check-label {\n");
      out.write("            display:flex; align-items:center; gap:0.6rem; cursor:pointer;\n");
      out.write("        }\n");
      out.write("        input[type=\"checkbox\"] {\n");
      out.write("            appearance:none; -webkit-appearance:none;\n");
      out.write("            width:18px; height:18px; border-radius:5px;\n");
      out.write("            border:1.5px solid var(--border);\n");
      out.write("            background:var(--surface);\n");
      out.write("            cursor:pointer; position:relative;\n");
      out.write("            transition:all 0.2s var(--ease);\n");
      out.write("            flex-shrink:0;\n");
      out.write("        }\n");
      out.write("        input[type=\"checkbox\"]:checked {\n");
      out.write("            background:var(--cyan); border-color:var(--cyan);\n");
      out.write("        }\n");
      out.write("        input[type=\"checkbox\"]:checked::after {\n");
      out.write("            content:'✓'; position:absolute;\n");
      out.write("            inset:0; display:flex; align-items:center; justify-content:center;\n");
      out.write("            font-size:11px; color:var(--bg); font-weight:700;\n");
      out.write("        }\n");
      out.write("        .check-txt { font-size:0.86rem; color:var(--txt2); }\n");
      out.write("        .forgot-a {\n");
      out.write("            font-size:0.84rem; color:var(--cyan);\n");
      out.write("            transition:color 0.2s;\n");
      out.write("        }\n");
      out.write("        .forgot-a:hover { color:#fff; }\n");
      out.write("\n");
      out.write("        /* Submit */\n");
      out.write("        .btn-submit {\n");
      out.write("            font-family:var(--font); font-size:1rem; font-weight:700;\n");
      out.write("            color:var(--bg); background:var(--cyan);\n");
      out.write("            border:none; padding:0.9rem; border-radius:12px; width:100%;\n");
      out.write("            cursor:pointer; transition:all 0.25s var(--spring);\n");
      out.write("            display:flex; align-items:center; justify-content:center; gap:0.5rem;\n");
      out.write("            position:relative; overflow:hidden; margin-top:0.4rem;\n");
      out.write("        }\n");
      out.write("        .btn-submit:hover {\n");
      out.write("            transform:translateY(-3px); box-shadow:0 14px 36px rgba(0,212,170,0.4);\n");
      out.write("        }\n");
      out.write("        .btn-submit:active { transform:translateY(-1px); }\n");
      out.write("        .btn-submit .btn-ico { transition:transform 0.25s var(--spring); }\n");
      out.write("        .btn-submit:hover .btn-ico { transform:translateX(4px); }\n");
      out.write("        .btn-submit.loading { pointer-events:none; opacity:0.8; }\n");
      out.write("\n");
      out.write("        /* Divider */\n");
      out.write("        .divider {\n");
      out.write("            display:flex; align-items:center; gap:1rem; color:var(--txt3);\n");
      out.write("            font-size:0.78rem; text-transform:uppercase; letter-spacing:0.1em;\n");
      out.write("        }\n");
      out.write("        .divider::before, .divider::after {\n");
      out.write("            content:''; flex:1; height:1px; background:var(--border);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .footer-txt {\n");
      out.write("            text-align:center; font-size:0.88rem; color:var(--txt2);\n");
      out.write("            position:relative; z-index:1;\n");
      out.write("        }\n");
      out.write("        .footer-txt a { color:var(--cyan); font-weight:600; transition:color 0.2s; }\n");
      out.write("        .footer-txt a:hover { color:#fff; }\n");
      out.write("\n");
      out.write("        /* ── TOAST ── */\n");
      out.write("        .toast {\n");
      out.write("            position:fixed; bottom:2rem; right:2rem; z-index:9999;\n");
      out.write("            padding:1rem 1.4rem; border-radius:14px;\n");
      out.write("            background:var(--bg3); border:1px solid var(--border);\n");
      out.write("            display:flex; align-items:center; gap:0.75rem;\n");
      out.write("            font-size:0.9rem; box-shadow:0 12px 40px rgba(0,0,0,0.5);\n");
      out.write("            animation:toastIn 0.35s var(--spring) both;\n");
      out.write("            max-width:320px;\n");
      out.write("        }\n");
      out.write("        .toast.err-toast { border-color:rgba(255,71,87,0.4); }\n");
      out.write("        .toast-ico { font-size:1.1rem; flex-shrink:0; }\n");
      out.write("\n");
      out.write("        /* ── ANIMATIONS ── */\n");
      out.write("        @keyframes slideUp {\n");
      out.write("            from { opacity:0; transform:translateY(30px); }\n");
      out.write("            to { opacity:1; transform:translateY(0); }\n");
      out.write("        }\n");
      out.write("        @keyframes errPop { from { transform:translateX(-6px); } to { transform:translateX(0); } }\n");
      out.write("        @keyframes toastIn {\n");
      out.write("            from { opacity:0; transform:translateY(20px) scale(0.92); }\n");
      out.write("            to { opacity:1; transform:translateY(0) scale(1); }\n");
      out.write("        }\n");
      out.write("        @keyframes spin { to { transform:rotate(360deg); } }\n");
      out.write("        @keyframes rippleOut { to { transform:scale(1); opacity:0; } }\n");
      out.write("\n");
      out.write("        /* ── RESPONSIVE ── */\n");
      out.write("        @media (max-width:900px) {\n");
      out.write("            .auth-page { grid-template-columns:1fr; }\n");
      out.write("            .auth-left { display:none; }\n");
      out.write("            .auth-right { padding:2rem 1.5rem; }\n");
      out.write("        }\n");
      out.write("        @media (max-width:480px) {\n");
      out.write("            header { padding:0 1rem; }\n");
      out.write("            .auth-card { padding:2rem 1.4rem; }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"orb orb1\"></div>\n");
      out.write("<div class=\"orb orb2\"></div>\n");
      out.write("\n");
      out.write("<!-- ══ HEADER ══ -->\n");
      out.write("<header>\n");
      out.write("    <a href=\"index.jsp\" class=\"logo\">\n");
      out.write("        <span class=\"logo-a\">Ace</span><span class=\"logo-b\">Bank</span>\n");
      out.write("    </a>\n");
      out.write("    <div class=\"hdr-links\">\n");
      out.write("        <a href=\"index.jsp\" class=\"nav-a\">Home</a>\n");
      out.write("        <a href=\"sign-up.jsp\" class=\"btn-nav\">Join Now</a>\n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<!-- ══ AUTH PAGE ══ -->\n");
      out.write("<div class=\"auth-page\">\n");
      out.write("\n");
      out.write("    <!-- Left panel -->\n");
      out.write("    <div class=\"auth-left\">\n");
      out.write("        <div class=\"auth-left-inner\">\n");
      out.write("            <div class=\"brand-title\">Secure.<br><span>Smart. Simple.</span></div>\n");
      out.write("            <p class=\"brand-sub\">Your financial life, simplified. AceBank gives you complete control over your money with zero complexity.</p>\n");
      out.write("            <div class=\"feat-list\">\n");
      out.write("                <div class=\"feat-item\">\n");
      out.write("                    <div class=\"feat-ico-wrap\">🔐</div>\n");
      out.write("                    <div class=\"feat-txt\">\n");
      out.write("                        <strong>Multi-Factor Auth</strong>\n");
      out.write("                        Bank-grade security on every login\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feat-item\">\n");
      out.write("                    <div class=\"feat-ico-wrap\">⚡</div>\n");
      out.write("                    <div class=\"feat-txt\">\n");
      out.write("                        <strong>Instant Access</strong>\n");
      out.write("                        View balance and transactions in real-time\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feat-item\">\n");
      out.write("                    <div class=\"feat-ico-wrap\">🛡️</div>\n");
      out.write("                    <div class=\"feat-txt\">\n");
      out.write("                        <strong>Fraud Protection</strong>\n");
      out.write("                        AI-powered monitoring around the clock\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Right: form -->\n");
      out.write("    <div class=\"auth-right\">\n");
      out.write("        <div class=\"auth-card\">\n");
      out.write("            <div class=\"card-icon\">🔑</div>\n");
      out.write("            <h1 class=\"card-h\">Welcome back</h1>\n");
      out.write("            <p class=\"card-sub\">Sign in to access your AceBank account.</p>\n");
      out.write("\n");
      out.write("            <form class=\"form\" action=\"Login\" method=\"POST\" id=\"loginForm\" novalidate>\n");
      out.write("\n");
      out.write("                <div class=\"field\">\n");
      out.write("                    <label for=\"accNo\">Account Number</label>\n");
      out.write("                    <div class=\"input-wrap\">\n");
      out.write("                        <input type=\"text\" id=\"accNo\" name=\"accountNumber\"\n");
      out.write("                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${savedAccount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" autocomplete=\"username\"\n");
      out.write("                               placeholder=\"Enter your account number\">\n");
      out.write("                        <span class=\"input-ico\">🏦</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"field-err\" id=\"accErr\">\n");
      out.write("                        <span>⚠</span> Account number is required\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"field\">\n");
      out.write("                    <label for=\"pass\">Password</label>\n");
      out.write("                    <div class=\"input-wrap\">\n");
      out.write("                        <input type=\"password\" id=\"pass\" name=\"password\"\n");
      out.write("                               autocomplete=\"current-password\" placeholder=\"••••••••••\">\n");
      out.write("                        <span class=\"input-ico\">🔒</span>\n");
      out.write("                        <button type=\"button\" class=\"eye-btn\" id=\"eyeBtn\" aria-label=\"Toggle password visibility\">👁</button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"field-err\" id=\"passErr\">\n");
      out.write("                        <span>⚠</span> Password is required\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"check-row\">\n");
      out.write("                    <label class=\"check-label\">\n");
      out.write("                        <input type=\"checkbox\" name=\"rememberMe\" id=\"remember\"\n");
      out.write("                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty savedAccount ? 'checked' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\n");
      out.write("                        <span class=\"check-txt\">Remember me</span>\n");
      out.write("                    </label>\n");
      out.write("                    <a href=\"ForgotPassword.jsp\" class=\"forgot-a\">Forgot password?</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <button type=\"submit\" class=\"btn-submit\" id=\"submitBtn\">\n");
      out.write("                    <span class=\"btn-lbl\">Sign In</span>\n");
      out.write("                    <svg class=\"btn-ico\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"><path d=\"M5 12h14M12 5l7 7-7 7\"/></svg>\n");
      out.write("                </button>\n");
      out.write("\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <div style=\"margin-top:1.5rem; position:relative; z-index:1;\">\n");
      out.write("                <p class=\"footer-txt\">Don't have an account? <a href=\"sign-up.jsp\">Create one free</a></p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("// ── Password toggle ──\n");
      out.write("const eye = document.getElementById('eyeBtn');\n");
      out.write("const passInput = document.getElementById('pass');\n");
      out.write("eye && eye.addEventListener('click', () => {\n");
      out.write("    const show = passInput.type === 'password';\n");
      out.write("    passInput.type = show ? 'text' : 'password';\n");
      out.write("    eye.textContent = show ? '🙈' : '👁';\n");
      out.write("});\n");
      out.write("\n");
      out.write("// ── Form validation ──\n");
      out.write("const form = document.getElementById('loginForm');\n");
      out.write("const accInput = document.getElementById('accNo');\n");
      out.write("\n");
      out.write("function showErr(input, errEl) {\n");
      out.write("    input.classList.add('err');\n");
      out.write("    errEl.classList.add('show');\n");
      out.write("}\n");
      out.write("function clearErr(input, errEl) {\n");
      out.write("    input.classList.remove('err');\n");
      out.write("    errEl.classList.remove('show');\n");
      out.write("}\n");
      out.write("\n");
      out.write("[accInput, passInput].forEach(inp => {\n");
      out.write("    inp.addEventListener('input', () => {\n");
      out.write("        const errId = inp.id === 'accNo' ? 'accErr' : 'passErr';\n");
      out.write("        if (inp.value.trim()) clearErr(inp, document.getElementById(errId));\n");
      out.write("    });\n");
      out.write("});\n");
      out.write("\n");
      out.write("form.addEventListener('submit', function(e) {\n");
      out.write("    let valid = true;\n");
      out.write("    if (!accInput.value.trim()) {\n");
      out.write("        showErr(accInput, document.getElementById('accErr')); valid = false;\n");
      out.write("    }\n");
      out.write("    if (!passInput.value.trim()) {\n");
      out.write("        showErr(passInput, document.getElementById('passErr')); valid = false;\n");
      out.write("    }\n");
      out.write("    if (!valid) { e.preventDefault(); return; }\n");
      out.write("\n");
      out.write("    const btn = document.getElementById('submitBtn');\n");
      out.write("    btn.classList.add('loading');\n");
      out.write("    btn.innerHTML = `\n");
      out.write("        <svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\"\n");
      out.write("             style=\"animation:spin 0.8s linear infinite\">\n");
      out.write("          <path d=\"M21 12a9 9 0 11-6.219-8.56\"/>\n");
      out.write("        </svg>\n");
      out.write("        Signing in…\n");
      out.write("    `;\n");
      out.write("});\n");
      out.write("\n");
      out.write("// ── Input focus animation ──\n");
      out.write("document.querySelectorAll('input[type=\"text\"], input[type=\"password\"]').forEach(inp => {\n");
      out.write("    inp.addEventListener('focus', () => {\n");
      out.write("        inp.closest('.field').style.transform = 'translateY(-1px)';\n");
      out.write("        inp.closest('.field').style.transition = 'transform 0.2s ease';\n");
      out.write("    });\n");
      out.write("    inp.addEventListener('blur', () => {\n");
      out.write("        inp.closest('.field').style.transform = '';\n");
      out.write("    });\n");
      out.write("});\n");
      out.write("\n");
      out.write("// ── Ripple ──\n");
      out.write("document.querySelectorAll('.btn-submit,.btn-nav').forEach(btn => {\n");
      out.write("    btn.addEventListener('click', function(e) {\n");
      out.write("        const r = this.getBoundingClientRect();\n");
      out.write("        const sz = Math.max(r.width, r.height)*2;\n");
      out.write("        const rp = document.createElement('span');\n");
      out.write("        rp.style.cssText = `position:absolute;border-radius:50%;pointer-events:none;\n");
      out.write("            width:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sz}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("px;height:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sz}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("px;\n");
      out.write("            left:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.clientX-r.left-sz/2}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("px;top:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.clientY-r.top-sz/2}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("px;\n");
      out.write("            background:rgba(255,255,255,0.2);transform:scale(0);\n");
      out.write("            animation:rippleOut 0.65s ease-out forwards;`;\n");
      out.write("        this.style.cssText += ';position:relative;overflow:hidden;';\n");
      out.write("        this.appendChild(rp);\n");
      out.write("        setTimeout(() => rp.remove(), 700);\n");
      out.write("    });\n");
      out.write("});\n");
      out.write("const rs = document.createElement('style');\n");
      out.write("rs.textContent = '@keyframes rippleOut{to{transform:scale(1);opacity:0;}} @keyframes spin{to{transform:rotate(360deg);}}';\n");
      out.write("document.head.appendChild(rs);\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
