# Email Configuration
mail.default.address=
mail.google.app.password=
# Database Configuration
db.url=
db.user=
db.password=
db.script.path=
db.mysql.driver=

# SMTP Server Settings
mail.smtp.host=
mail.smtp.port=
mail.smtp.auth=
mail.smtp.starttls.enable=
mail.smtp.connection-timeout=
mail.smtp.timeout=

